video_encoder=h264_nvenc
audio_encoder=aac

; cf. `ffmpeg -h encoder=[ENCODER]
video_quality=-cq 19 -b:v 2048k -maxrate 2048k -multipass 1
audio_quality=-b:a 128k -ar 48k

preset=p5

framerate=60
aspect=16:9

; 2passの設定(0=disable, 1=quaterRes, 2=fullRes) ; vbr, qp
multipass_type=0

; 適応量子化の設定 (spatial, temporal:`aq_type=`で無効化)
aq_type=
aq_strength=6

; 色空間についての設定
color_fmt=yuv420p
color_range=tv

; その他、任意のffmpegオプション
option=-hide_banner -movflags +faststart