video_encoder=h264_nvenc
audio_encoder=aac

; cf. `ffmpeg -h encoder=[ENCODER]
video_options=-cq 23 -spatial-aq 1 -b_ref_mode 1 -multipass 1
audio_options=-b:a 128k -ar 48k

framerate=60
aspect=16:9

color_fmt=yuv420p
color_range=tv

; その他
option=-hide_banner -movflags +faststart